C8Y:
    baseUrl: ${C8Y_BASEURL}
gateway:
    identifier: ${OPCUA_GATEWAY_IDENTIFIER}
    name: ${OPCUA_GATEWAY_NAME}
    db:
        baseDir: ./data
    thinEdge:
      enabled: true
      mqttServerURL: tcp://${MQTT_BROKER}
      deviceId: ${DEVICE_ID}